name       : mrboom
version    : '4.8'
release    : 6
source     :
    - https://github.com/Javanaise/mrboom-libretro/archive/4.8.tar.gz : ca41016ced65840d364556ba7477f1d1af2d5b72c98dd1bdf406bea75ad28b71
license    : MIT
component  : games.arcade
summary    : Mr.Boom is a 8 players Bomberman clone for RetroArch/Libretro
description: |
    Mr.Boom is a 8 players Bomberman clone for RetroArch/Libretro
builddeps  :
    - pkgconfig(libmodplug)
    - pkgconfig(minizip)
    - pkgconfig(SDL2_mixer)
rundeps    :
    - libmodplug
setup      : |
    %make clean
build      : |
    %patch -p1 < $pkgfiles/build_fix.patch
    %make mrboom LIBSDL2=1
install    : |
    %make_install PREFIX=%PREFIX% MANDIR=/share/man/man6
    install -Dm00644 Assets/mrboom.png -t $installdir/usr/share/pixmaps
    install -Dm00644 Assets/mrboom.desktop -t $installdir/usr/share/applications
    install -Dm00644 Assets/mrboom.appdata.xml -t $installdir/usr/share/metainfo
